"['Claus', 'Pahl', '+39', '0471 016177', 'Claus.Pahl@unibz.it', '0000', 'Software Engineering']"
"['Diego', 'Calvanese', '+39', '0471 016160', 'Diego.Calvanese@unibz.it', '0000', 'Data and Process Modeling for Business Informatics', 'Introduction to Databases', 'PhD course/seminar 1st year']"
"['Antonella', 'De', 'Angeli', '+39', '0471 016041', 'Antonella.DeAngeli@unibz.it', '0000', 'Elements of Computer Science for Communications', 'Human-Centered Computing', 'PhD course/seminar 1st year', 'User Research']"
"['Enrico', 'Franconi', '+39', '0471 016120', None, '0000', 'Artificial Intelligence', 'PhD course/seminar 1st year', 'Semantic Technologies and Linked Data']"
"['Johann', 'Gamper', '+39', '0471 016140', 'Johann.Gamper@unibz.it', '0000', 'Database Management Systems']"
"['Antonio', 'Liotta', '+39', None, 'Antonio.Liotta@unibz.it', '0000', 'Computer Networks', 'Programming for Data Analytics', 'Programming for Data Analytics']"
"['Werner', 'Nutt', '+39', '0471 016126', 'Werner.Nutt@unibz.it', '0000', 'Data Structures & Algorithms', 'Data Structures and Algorithms', 'PhD course/seminar 1st year', 'Probability Theory and Statistics', 'Probability Theory and Statistics']"
"['Francesco', 'Ricci', '+39', '0471 016971', 'Francesco.Ricci@unibz.it', '0000', 'Computer Programming', 'Introduction to Programming', 'Recommender Systems']"
"['Barbara', 'Russo', '+39', '0471 016170', 'Barbara.Russo@unibz.it', '0000', 'Information Retrieval', 'Tools and Techniques for Software Testing', 'Verification and Reliability for Dependable Systems (FSE)']"
"['Markus', 'Zanker', '+39', '0471 016977', 'Markus.Zanker@unibz.it', '0000', 'ERP Systems and IT Service Management', 'Information Retrieval', 'Web and Internet Engineering', 'Web and Internet Engineering', 'Web and Internet Engineering']"
"['Alessandro', 'Artale', '+39', '0471 016150', 'Alessandro.Artale@unibz.it', '0000', 'Applied Formal Methods', 'Formal Languages and Compilers', 'Operating Systems']"
"['Bruno', 'Carpentieri', '+39', '0471 016027', 'Bruno.Carpentieri@unibz.it', '0000', 'Introduction to Linear Algebra and Discrete Mathematics', 'Linear Algebra', 'Preparatory Course in Mathematics']"
"['Giancarlo', 'Guizzardi', '+39', '0471 016187', 'Giancarlo.Guizzardi@unibz.it', '0000', 'IT Management and Enterprise Modeling', 'Programming Project']"
"['Fabrizio', 'Maria', 'Maggi', None, None, None, '0000', 'Information Security', 'Management of System Security and Networks']"
"['Marco', 'Montali', '+39', '0471 016116', 'marco.montali@unibz.it', '0000', 'Capstone Project', 'Data and Process Modeling for Business Informatics', 'PhD course/seminar 1st year', 'Programming Project', 'Web and Internet Engineering']"
"['Romain', 'Robbes', '+39', '0471 016025', 'RRobbes@unibz.it', '0000', 'Engineering of Mobile Systems', 'Engineering of Mobile Systems', 'Software Maintenance and Evolution (ATSSE)']"
"['Xiaofeng', 'Wang', '+39', '0471 016181', 'Xiaofeng.Wang@unibz.it', '0000', 'Agile Software Development', 'Agile Software Development (ST)', 'Lean Start-Up and Entrepreneurship (ST)']"
"['Sergio', 'Tessaris', '+39', '0471 016125', 'Sergio.Tessaris@unibz.it', '0000', 'Artificial Intelligence - Methods and Applications']"
"['Attaullah', 'Buriro', None, None, 'Attaullah.Buriro@unibz.it', '0000', 'Software and Systems Security (ATSSE)', 'Systems Security']"
"['Matteo', 'Camilli', '+39', '0471 016179', 'Matteo.Camilli@unibz.it', '0000', 'Systems Engineering', 'Verification and Reliability for Dependable Systems (FSE)']"
"['Matteo', 'Ceccarello', '+39', '0471 016141', 'Matteo.Ceccarello@unibz.it', '0000', 'Data Visualisation and Exploration', 'Data Visualization and Exploration', 'PhD course/seminar 1st year']"
"['Roberto', 'Confalonieri', '+39', '0471 016244', 'Roberto.Confalonieri@unibz.it', '0000', 'Advanced Topics in Machine Learning', 'Discrete Mathematics']"
"['Daniela', ""D'Auria"", None, None, 'Daniela.DAuria@unibz.it', '0000']"
"['Anton', 'Dignös', '+39', '0471 016142', 'Anton.Dignoes@unibz.it', '0000', 'Advanced Data Management Technologies']"
"['Nabil', 'El', 'Ioini', '+39', '0471 016138', 'nelioini@unibz.it', '0000', 'Cloud Computing and Distributed Systems (ATSSE)']"
"['Paolo', 'Felli', '+39', '0471 016152', 'Paolo.Felli@unibz.it', '0000', 'Introduction to Databases for Business Informatics']"
"['Ilenia', 'Fronza', '+39', '0471 016247', 'Ilenia.Fronza@unibz.it', '0000', 'Project and Teamwork Management (IT)', 'Research Methods and Technology Transfer (SSER)', 'Scientific Writing and Communication (IT)']"
"['Pietro', 'Galliani', None, None, 'Pietro.Galliani@unibz.it', '0000', 'Data Structures & Algorithms', 'Probability Theory and Statistics', 'Programming Paradigms']"
"['Rosella', 'Gennari', '+39', '0471 016964', 'Rosella.Gennari@unibz.it', '0000', 'Computer programming (Python)']"
"['Andrea', 'Alexander', 'Janes', '+39', '0471 016132', 'Andrea.Janes@unibz.it', '0000', 'Application Engineering for Business Informatics', 'Contemporary Software Development (FSE)']"
"['Mouna', 'Kacimi', 'El', 'Hassani', '+39', '0471 016114', 'Mouna.Kacimi@unibz.it', '0000', 'Machine Learning']"
"['Oliver', 'Kutz', '+39', '0471 016124', 'Oliver.Kutz@unibz.it', '0000', 'Discrete Mathematics']"
"['Davide', 'Lanti', '+39', '0471 016135', 'Davide.Lanti@unibz.it', '0000', 'Introduction to Databases', 'Semantic Technologies and Linked Data']"
"['Paola', 'Lecca', '+39', '0471 016162', 'Paola.Lecca@unibz.it', '0000', 'Analysis', 'Statistics for Data Science']"
"['Elisa', 'Marengo', '+39', '0471 016171', 'Elisa.Marengo@unibz.it', '0000', 'Programming Paradigms']"
"['Eduardo', 'Martins', 'Guerra', None, None, 'Eduardo.MartinsGuerra@unibz.it', '0000', 'Requirements and Design for Dependable Systems (FSE)', 'Software Systems Architecture', 'Systems Engineering']"
"['Alessandra', 'Melonio', '+39', '0471 016222', 'Alessandra.Melonio@unibz.it', '0000']"
"['Maria', 'Menendez', 'Blanco', None, None, 'Maria.MenendezBlanco@unibz.it', '0000', 'Human-Centered Computing']"
"['Alessandro', 'Mosca', '+39', '0471 016268', 'Alessandro.Mosca@unibz.it', '0000']"
"['Tiago', 'Prince', 'Sales', None, None, 'Tiago.PrinceSales@unibz.it', '0000', 'Programming Project']"
"['Ognjen', 'Savkovic', '+39', '0471 016167', 'Ognjen.Savkovic@unibz.it', '0000', 'Analysis']"
"['Michele', 'Segata', None, None, 'Michele.Segata@unibz.it', '0000', 'Computer Networks', 'Computer Programming', 'Introduction to Programming', 'Operating Systems']"
"['Nicolas', 'Troquard', None, None, 'Nicolas.Troquard@unibz.it', '0000', 'Decision Making and Support Systems']"
"['Flavio', 'Vella', '+39', '0471 016153', 'Flavio.Vella@unibz.it', '0000', 'Computer Systems Architecture', 'Introduction to Parallel Computing', 'Introduction to parallel computing']"
"['Guohui', 'Xiao', '+39', '0471 016267', 'Guohui.Xiao@unibz.it', '0000', 'Real-Time Big Data Processing']"
"['Floriano', 'Luca', 'Zini', '+39', '0471 016236', 'floriano.zini@unibz.it', '0000']"
"['Valentina', 'Adami', None, None, 'Valentina.Adami@unibz.it', '0000', 'Advanced Scientific English', 'Advanced Scientific English', 'Advanced Scientific English', 'English 1', 'Foreign Language (English) - Specialized Language course', 'Introduction to academic writing', 'Scientific English']"
"['Riccardo', 'Billero', None, None, 'Riccardo.Billero@unibz.it', '0000', 'Applied Informatics', 'Multimedia Systems', 'Web and Internet Engineering']"
"['David', 'Bramini', None, None, 'David.Bramini@unibz.it', '0000']"
"['Peter', 'James', 'Brannick', None, None, 'Peter.Brannick@unibz.it', '0000', 'English as a Foreign Language - Specialized Language course', 'English for Computer Scientists 1', 'English for Computer Scientists 2', 'Scientific language skills']"
"['Lorenzo', 'Carpanè', None, None, 'Lorenzo.Carpane@unibz.it', '0000', 'Italian for Computer Scientists']"
"['Alberto', 'Cavaliere', '+39', '0471 013278', 'Alberto.Cavaliere@unibz.it', '0000', 'Economics of Digital Markets']"
"['Silvia', 'Fissi', None, None, 'Silvia.Fissi@unibz.it', '0000', 'Accounting for the Public Sector', 'Introduction to Business Administration (IT)']"
"['Daniel', 'Gallo', None, None, 'Daniel.Gallo@unibz.it', '0000', 'German for Computer Scientist']"
