Begin;

INSERT INTO Subject Values

(DEFAULT,6 ,'Linear Algebra*'),
(DEFAULT,6 ,'Discrete Mathematics'),
(DEFAULT,9 ,'Computer Programming*'),
(DEFAULT,3 ,'English for Computer Scientists 1'),
(DEFAULT,6 ,'Computer Systems Architecture'),
(DEFAULT,6 ,'Analysis'),
(DEFAULT,6 ,'Web and Internet Engineering'),
(DEFAULT,6 ,'English for Computer Scientists 2'),
(DEFAULT,9 ,'Programming Project'),
(DEFAULT,6 ,'Operating Systems'),
(DEFAULT,3 ,'Maker Lab'),
(DEFAULT,6 ,'Introduction to Databases'),
(DEFAULT,6 ,'Probability Theory and Statistics'),
(DEFAULT,9 ,'Data Structures and Algorithms'),
(DEFAULT,6 ,'Italian for Computer Scientists / German for Computer Scientists'),
(DEFAULT,6 ,'Database Management Systems'),
(DEFAULT,6 ,'Formal Languages and Compilers'),
(DEFAULT,12 ,'Software Engineering'),
(DEFAULT,6 ,'Applied Computer Science 1'),
(DEFAULT,12 ,'Free Choice/Internship'),
(DEFAULT,12 ,'Applied Computer Science 2'),
(DEFAULT,6 ,'Computer Networks'),
(DEFAULT,6 ,'Module 1: Computational Mathematics(Computational Security)'),
(DEFAULT,6 ,'Module 2: Information Security(Computational Security)'),
(DEFAULT,3 ,'Project and Teamwork Management'),
(DEFAULT,3 ,'Scientific Writing and Communication'),
(DEFAULT,3 ,'Introduction to Business Administration'),
(DEFAULT,6 ,'Internship/Project for Thesis'),
(DEFAULT,9 ,'Thesis'),
(DEFAULT,6 ,'Software Systems Architecture(Software Architecture)'),
(DEFAULT,6 ,'Engineering of Mobile Systems(Mobile and Physical Systems)'),
(DEFAULT,6 ,'Foundations of Artificial Intelligence(Artificial Intelligence)'),
(DEFAULT,6 ,'Knowledge Representation(Intelligent Agents)'),
(DEFAULT,6 ,'Introduction to Linear Algebra and Discrete Mathematics'),
(DEFAULT,9 ,'Introduction to Programming'),
(DEFAULT,6 ,'Accounting for Decision Making'),
(DEFAULT,9 ,'Economics of Digital Markets'),
(DEFAULT,6 ,'Introduction to Analysis and Optimization Techniques'),
(DEFAULT,0 ,'Module 1: Data and Process Modeling for Business Informatics(Modeling and Databases)'),
(DEFAULT,6 ,'Application Engineering for Business Informatics'),
(DEFAULT,6 ,'Web and Internet Engineering'),
(DEFAULT,0 ,"'Module 1: Strategic Management and Digital Business(Introduction to Digital Business, Strategy and Management )'"),
(DEFAULT,12 ,'Specialization in Digital Finance and Financial Markets or in Digital Market and Advertising*'),
(DEFAULT,6 ,'Data Structures and Algorithms'),
(DEFAULT,6 ,'Probability Theory and Statistics'),
(DEFAULT,6 ,'Management of System Security and Networks'),
(DEFAULT,3 ,'English for Informatics and Digital Business'),
(DEFAULT,0 ,'Module 1: IT Management and Enterprise Modeling(IT Management and ERP Systems)'),
(DEFAULT,6 ,'Engineering of Mobile Systems'),
(DEFAULT,0 ,'Module 1: Introduction to Data Mining(Data Mining and Decision Making)'),
(DEFAULT,12 ,'Free Choice'),
(DEFAULT,3 ,'Legal Aspects of IT'),
(DEFAULT,3 ,'Italian/German for Informatics and Digital Business'),
(DEFAULT,6 ,'Seminar in Business Informatics and Information Systems'),
(DEFAULT,6 ,'Specialisation in Digital Finance and Financial Markets or in Digital Market and Advertising*'),
(DEFAULT,6 ,'Software Project Management'),
(DEFAULT,6 ,'Internship/Project'),
(DEFAULT,5 ,'Thesis'),
(DEFAULT,6 ,'Advanced Data Management Technologies'),
(DEFAULT,6 ,'Artificial Intelligence – Methods and Applications'),
(DEFAULT,6 ,'Data Visualisation and Exploration(Programming and Visualisation for Data Analytics)'),
(DEFAULT,6 ,'Statistics for Data Science'),
(DEFAULT,6 ,'Human-Centered Computing'),
(DEFAULT,6 ,'Information Retrieval'),
(DEFAULT,6 ,'Machine Learning'),
(DEFAULT,6 ,'Systems Security'),
(DEFAULT,6 ,'Optional Course*'),
(DEFAULT,6 ,'Data Integration(Data Curation)'),
(DEFAULT,6 ,'Capstone Project'),
(DEFAULT,6 ,'Optional Course*'),
(DEFAULT,6 ,'Free Choice**'),
(DEFAULT,4 ,'Advanced English for Scientific Communication'),
(DEFAULT,6 ,'Free Choice**'),
(DEFAULT,20 ,'Thesis'),
(DEFAULT,6 ,'Advanced Topics in Machine Learning'),
(DEFAULT,6 ,'Agile Software Development'),
(DEFAULT,6 ,'Computational Linguistics'),
(DEFAULT,12 ,'Data and Information Modelling'),
(DEFAULT,6 ,'Data Maintenance and Evolution'),
(DEFAULT,6 ,'Data Scientist Toolbox'),
(DEFAULT,6 ,'Decision Making and Support Systems'),
(DEFAULT,6 ,'Development of Data Products'),
(DEFAULT,6 ,'Enterprise Architecture'),
(DEFAULT,6 ,'Formal Verification of Software and Systems'),
(DEFAULT,6 ,'Intelligent Agents'),
(DEFAULT,6 ,'Introduction to Parallel Computing'),
(DEFAULT,6 ,'Lean Start-Up and Entrepreneurship'),
(DEFAULT,6 ,'Management of Temporal and Spatial Data'),
(DEFAULT,6 ,'Process-Aware Information Systems'),
(DEFAULT,6 ,'Process Mining'),
(DEFAULT,6 ,'Real-Time Big Data Processing'),
(DEFAULT,6 ,'Recommender Systems'),
(DEFAULT,6 ,'Research Methods and Technology Transfer'),
(DEFAULT,6 ,'Semantic Technologies and Linked Data'),
(DEFAULT,6 ,'Simulation and Modelling'),
(DEFAULT,6 ,'Web and Text Mining'),
(DEFAULT,6 ,'Advanced Data Management Technologies'),
(DEFAULT,6 ,'Algorithms for Data Processing'),
(DEFAULT,6 ,'M-1 Data and Process Modelling(Data and Information Modelling)'),
(DEFAULT,6 ,'Artificial Intelligence - Methods and Applications'),
(DEFAULT,6 ,'Enterprise Architectures'),
(DEFAULT,6 ,'Semantic Technologies and Linked Data'),
(DEFAULT,6 ,'Machine Learning'),
(DEFAULT,6 ,'Systems Security'),
(DEFAULT,6 ,'Optional Course*'),
(DEFAULT,6 ,'Data Integration(Data Curation)'),
(DEFAULT,6 ,'Capstone Project'),
(DEFAULT,6 ,'Optional Course*'),
(DEFAULT,6 ,'Free Choice**'),
(DEFAULT,6 ,'Free Choice**'),
(DEFAULT,4 ,'Advanced English for Scientific Communication'),
(DEFAULT,20 ,'Thesis'),
(DEFAULT,6 ,'Advanced Topics in Machine Learning'),
(DEFAULT,6 ,'Agile Software Development'),
(DEFAULT,6 ,'Computational Linguistics'),
(DEFAULT,12 ,'Data Maintenance and Evolution'),
(DEFAULT,6 ,'Data Scientist Toolbox'),
(DEFAULT,6 ,'Decision Making and Support Systems'),
(DEFAULT,6,'Development of Data Products'),
(DEFAULT,6,'Formal Verification of Software and Systems'),
(DEFAULT,6,'Human-Centered Computing'),
(DEFAULT,6,'Information Retrieval'),
(DEFAULT,6,'Intelligent Agents'),
(DEFAULT,6,'Introduction to Parallel Computing'),
(DEFAULT,6,'Lean Start-Up and Entrepreneurship'),
(DEFAULT,6,'Management of Temporal and Spatial Data'),
(DEFAULT,6,'Process Mining'),
(DEFAULT,6,'Process-Aware Information Systems'),
(DEFAULT,6,'Programming and Visualisation for Data Analytics'),
(DEFAULT,6,'Real-Time Big Data Processing'),
(DEFAULT,6,'Recommender Systems'),
(DEFAULT,6,'Research Methods and Technology Transfer'),
(DEFAULT,6,'Simulation and Modelling'),
(DEFAULT,6,'Web and Text Mining'),
(DEFAULT,6 ,'M1 Data Visualization and Exploration(Programming and Visualization for Data Analytics)'),
(DEFAULT,6 ,'Contemporary Software Development'),
(DEFAULT,6 ,'Requirements and Design for Dependable Systems'),
(DEFAULT,6 ,'Alternatives from Catalogue'),
(DEFAULT,6 ,'Verification and Reliability for Dependable Systems'),
(DEFAULT,6 ,'M1: Embedded Systems Design and Implementation(Systems Design and Implementation)'),
(DEFAULT,6 ,'Software and Systems Security'),
(DEFAULT,6 ,'Cloud Computing and Distributed Systems'),
(DEFAULT,6 ,'Research Methods and Technology Transfer'),
(DEFAULT,12 ,'Free Choice Courses'),
(DEFAULT,6 ,'Internship'),
(DEFAULT,6 ,'Alternatives from Catalogue'),
(DEFAULT,30 ,'Thesis'),
(DEFAULT,6 ,'Module WUP ART Praxis(Project Warm-Up ART)'),
(DEFAULT,8 ,'Artistic Drawing 2D - 1 and 2'),
(DEFAULT,6 ,'Artistic Practices 1 and 2'),
(DEFAULT,6 ,'Typography and Graphics'),
(DEFAULT,6 ,'History of Contemporary Art 1'),
(DEFAULT,5 ,'History of Contemporary Art 2'),
(DEFAULT,6 ,'Drawing and Storytelling'),
(DEFAULT,6 ,'Interaction and Communication Design'),
(DEFAULT,6 ,'Artistic Productions 1 and 2'),
(DEFAULT,3 ,'Foreign Language - Linguistic Skills'),
(DEFAULT,6 ,'Descriptive Geometry ART'),
(DEFAULT,8 ,'Cultural Anthropology(1 Mandatory Course to be chosen among the Following)'),
(DEFAULT,3 ,'Foreign Language DES-ART 1 Italiano(1 Mandatory Course to be chosen among the Following)'),
(DEFAULT,2 ,'Seminar*'),
(DEFAULT,12 ,'Free Choice Courses**'),
(DEFAULT,8 ,"'Spaces and their Production(Studio A - ""Space"")'"),
(DEFAULT,8 ,"'Interaction/Performance(Studio B - ""Interact"")'"),
(DEFAULT,8 ,"'Photography-Video(Studio C – ""Image"")'"),
(DEFAULT,8 ,"'Curatorial Theory and Practices(Studio D - ""Exhibit"")'"),
(DEFAULT,9 ,'Degree Project'),
(DEFAULT,0 ,'Carpentry Workshop'),
(DEFAULT,0 ,'Metal Workshop'),
(DEFAULT,0 ,'Plastics Workshop'),
(DEFAULT,0 ,'Digital Modelling Workshop'),
(DEFAULT,0 ,'Print Workshop'),
(DEFAULT,0 ,'Cutting and Binding Workshop'),
(DEFAULT,0 ,'Photography Workshop'),
(DEFAULT,0 ,'Video Workshop'),
(DEFAULT,0 ,'Bankraum (Assembly space)'),
(DEFAULT,0 ,'Surface Treatment Workshop'),
(DEFAULT,,'Glass Workshop'),
(DEFAULT,6 ,'Module WUP DES Product Design(Project Warm-up DES)'),
(DEFAULT,8 ,'Drawing 3D CAD - 1 and 2'),
(DEFAULT,6 ,'Descriptive Geometry DES'),
(DEFAULT,6 ,'History of Design 1'),
(DEFAULT,5 ,'History of Design 2'),
(DEFAULT,6 ,'Typography and Graphics'),
(DEFAULT,6 ,'Interior and Exhibit Design'),
(DEFAULT,3 ,'Foreign Language - Linguistic Skills'),
(DEFAULT,6 ,'History of Contemporary Art 1'),
(DEFAULT,6 ,'Video and Post-Production(1 Mandatory Course to be chosen among the following)'),
(DEFAULT,6 ,'Digital Design: 3D CAD Advanced(1 Mandatory Course to be chosen among the following)'),
(DEFAULT,8 ,'Sociology of Social Change(1 Mandatory Course to be chosen among the following)'),
(DEFAULT,3 ,'Foreign Language DES - ART 1 Italiano(1 Mandatory Course to be chosen among the following)'),
(DEFAULT,2 ,'Seminar*'),
(DEFAULT,12 ,'Free Choice Courses**'),
(DEFAULT,8 ,'Product Design(Project Product design 1)'),
(DEFAULT,8 ,'Visual Communication(Project Visual Communication 1)'),
(DEFAULT,8 ,'Visual Communication(Project Visual Communication 2)'),
(DEFAULT,8 ,'Product Design(Project Product design 2)'),
(DEFAULT,9 ,'Degree Project'),
(DEFAULT,0 ,'Carpentry Workshop'),
(DEFAULT,0 ,'Metal Workshop'),
(DEFAULT,0 ,'Plastics Workshop'),
(DEFAULT,0 ,'Digital Modelling Workshop'),
(DEFAULT,0 ,'Print Workshop'),
(DEFAULT,0 ,'Cutting and Binding Workshop'),
(DEFAULT,0 ,'Photography Workshop'),
(DEFAULT,0 ,'Video Workshop'),
(DEFAULT,0 ,'Bankraum (Assembly Space) Workshop'),
(DEFAULT,0 ,'Surface Treatment Workshop'),
(DEFAULT,0 ,'Glass Workshop'),
(DEFAULT,12 ,'Project 1 in Eco-Social Design'),
(DEFAULT,6 ,'Design Research related to Project 1 and 2'),
(DEFAULT,12 ,'Project 2 in Eco-Social Design'),
(DEFAULT,9 ,"'Design 3(Thesis Project Phase 1: Research through Design, Exploration and Experimentation)'"),
(DEFAULT,6 ,'Web and Media Design'),
(DEFAULT,6 ,'Design and Production(1 Mandatory Course to be chosen among the following:)'),
(DEFAULT,6 ,'Political Ecology'),
(DEFAULT,6 ,'Ecosocial Economics'),
(DEFAULT,6 ,'Media Studies(2 Mandatory Courses to be chosen among the following:)'),
(DEFAULT,3 ,'English 1'),
(DEFAULT,12 ,'Free Choice Courses**'),
(DEFAULT,6 ,'Seminars***'),
(DEFAULT,18 ,'Degree Thesis****'),
(DEFAULT,0 ,'Carpentry Workshop'),
(DEFAULT,0 ,'Metal Workshop'),
(DEFAULT,0 ,'Plastics Workshop'),
(DEFAULT,0 ,'Digital Modelling Workshop'),
(DEFAULT,0 ,'Print Workshop'),
(DEFAULT,0 ,'Cutting and Binding Workshop'),
(DEFAULT,0 ,'Photography Workshop'),
(DEFAULT,0 ,'Video Workshop'),
(DEFAULT,0 ,'Assembly Space (Bankraum)'),
(DEFAULT,0 ,'Surface Treatment Workshop'),
(DEFAULT,0 ,'Glass Workshop'),
(DEFAULT,8 ,'Microeconomics'),
(DEFAULT,8 ,'Introduction to Accounting'),
(DEFAULT,6 ,'M-1 Mathematics for Economists(Mathematics for Economists)'),
(DEFAULT,8 ,'Macroeconomics'),
(DEFAULT,5 ,'Computer Science'),
(DEFAULT,8 ,'Introduction to Management'),
(DEFAULT,4 ,'Foreign Language 1 - Specialised Language course for Economics - Basic*'),
(DEFAULT,4 ,'Foreign Language 2 - Specialised Language course for Economics - Basic*'),
(DEFAULT,6 ,'M-1 Public Economic Law(Introduction to Legal Systems)'),
(DEFAULT,6 ,'M-1 Marketing(Marketing and Strategic Management)'),
(DEFAULT,6 ,'Financial Analysis'),
(DEFAULT,6 ,'Statistics'),
(DEFAULT,6 ,'Mathematics of Finance'),
(DEFAULT,3 ,'Foreign Language 1 - Specialised Language course for Economics - Advanced*'),
(DEFAULT,3 ,'Foreign Language 2 - Specialised Language course for Economics - Advanced*'),
(DEFAULT,12 ,'Free Choice Courses**'),
(DEFAULT,6 ,'Internship'),
(DEFAULT,6 ,'Economic Policy'),
(DEFAULT,6 ,'Industrial Economics'),
(DEFAULT,6 ,'Business Law'),
(DEFAULT,6 ,'Intermediate Financial Accounting(Typical Subject (one of the following):)'),
(DEFAULT,6 ,'Entrepreneurship and Innovation Management(Typical Subject (one of the following):)'),
(DEFAULT,6 ,'Financial Risk Management(Typical Subject (one of the following):)'),
(DEFAULT,6 ,'Econometrics for Economics(Complementary Subject (one of the following):)'),
(DEFAULT,6 ,'Contract Law(Complementary Subjects (two of the following):)'),
(DEFAULT,3 ,'Final Exam'),
(DEFAULT,8 ,'Economics 1 for PPE'),
(DEFAULT,6 ,'History of Economic Thought for PPE'),
(DEFAULT,6 ,'M-1 Mathematics A for PPE(Mathematics for PPE)'),
(DEFAULT,8 ,'Business Administration'),
(DEFAULT,8 ,'Economics 2 for PPE'),
(DEFAULT,8 ,'Comparative Politics'),
(DEFAULT,8 ,'Principles of Philosophy 1'),
(DEFAULT,3 ,'Foreign Language 1 - Specialized Language Course*'),
(DEFAULT,3 ,'Foreign Language 2 - Specialized Language Course*'),
(DEFAULT,3 ,'Information Systems and Data Management'),
(DEFAULT,6 ,'M-1 Public Law(European and Public Law)'),
(DEFAULT,8 ,'Statistics for PPE'),
(DEFAULT,8 ,'Principles of Philosophy 2'),
(DEFAULT,8 ,'Political Theory'),
(DEFAULT,6 ,'Applied Econometrics'),
(DEFAULT,7 ,'Decision Making and Ethics'),
(DEFAULT,3 ,'Foreign Language 1 - Advanced Specialized Language Course*'),
(DEFAULT,3 ,'Foreign Language 2 - Advanced Specialized Language Course*'),
(DEFAULT,12 ,'Free Choice Courses**'),
(DEFAULT,4 ,'Internship'),
(DEFAULT,6 ,'Economics Law'),
(DEFAULT,7 ,'Economic Policy and Institutions'),
(DEFAULT,7 ,'Political Economics (curr. Social Sciences)'),
(DEFAULT,3 ,'Introduction to Academic Writing'),
(DEFAULT,7 ,'International Economics(Typical Subject (one of the following):)'),
(DEFAULT,7 ,'Public Economics(Typical Subject (one of the following):)'),
(DEFAULT,5 ,'Final thesis'),
(DEFAULT,8 ,'Economics 1 for PPE'),
(DEFAULT,6 ,'History of Economic Thought for PPE'),
(DEFAULT,6 ,'M-1 Mathematics A for PPE(Mathematics for PPE)'),
(DEFAULT,8 ,'Business Administration'),
(DEFAULT,8 ,'Economics 2 for PPE'),
(DEFAULT,8 ,'Comparative Politics'),
(DEFAULT,8 ,'Principles of Philosophy 1'),
(DEFAULT,3 ,'Foreign Language 1  - Specialized Language course*'),
(DEFAULT,3 ,'Foreign Language 2  - Specialized Language course*'),
(DEFAULT,3 ,'Information Systems and Data Management'),
(DEFAULT,6 ,'M-1 Public Law(European and Public Law)'),
(DEFAULT,8 ,'Statistics for PPE'),
(DEFAULT,7 ,'Decision Making and Ethics'),
(DEFAULT,8 ,'Econometrics for PPE'),
(DEFAULT,7 ,'Financial Markets and Institutions for PPE'),
(DEFAULT,3 ,'Foreign Language 1 - Advanced Specialized Language Course*'),
(DEFAULT,3 ,'Foreign Language 2 - Advanced Specialized Language Course*'),
(DEFAULT,12 ,'Free Choice Courses**'),
(DEFAULT,4 ,'Internship'),
(DEFAULT,3 ,'Introduction to Academic Writing'),
(DEFAULT,7 ,'Economic Policy for PPE'),
(DEFAULT,7 ,'Labor Economics'),
(DEFAULT,6 ,'Banking and Financial Law'),
(DEFAULT,7 ,'International Economics(Typical Subject (one of the following):)'),
(DEFAULT,7 ,'Public Economics(Typical Subject (one of the following):)'),
(DEFAULT,7 ,'Theory of Science(Complementary Subject (one of the following):)'),
(DEFAULT,5 ,'Final Thesis'),
(DEFAULT,6 ,'Introduction to Management'),
(DEFAULT,6 ,'M-1 Mathematics for Economists TSE(Mathematics for Economists TSE)'),
(DEFAULT,6 ,'Tourism and Sport Law'),
(DEFAULT,8 ,'Introduction to Accounting for TSE'),
(DEFAULT,8 ,'Micro and Macroeconomics'),
(DEFAULT,8 ,'Marketing'),
(DEFAULT,6 ,"'Introduction to Tourism, Sport and Event Management'"),
(DEFAULT,3 ,'Foreign Language 1 – Communication and Presentation Skills in Specialized Language*'),
(DEFAULT,3 ,'Foreign Language 2 – Communication and Presentation Skills in Specialized Language*'),
(DEFAULT,6 ,'Managerial Economics for TSE'),
(DEFAULT,6 ,'Statistics for TSE'),
(DEFAULT,6 ,'Managerial Accounting'),
(DEFAULT,9 ,'Introduction to Finance'),
(DEFAULT,6 ,"'Foreign Language (Spanish, Russian or French)'"),
(DEFAULT,6 ,'M-1 Strategic Management(Entrepreneurship and Leadership)'),
(DEFAULT,6 ,'Economics of Sport and Events(Typical Subject (one of the following):)'),
(DEFAULT,6 ,'Experiential Tourism: current trends in food and wine(Typical Subject (one of the following):)'),
(DEFAULT,6 ,'Event Management and Planning(Complementary Subject (one of the following):)'),
(DEFAULT,6 ,'M-1 Foundations of Business Law(Business Law)'),
(DEFAULT,3 ,"'Technology, Media and Data in Tourism, Sports and Events'"),
(DEFAULT,6 ,'Sport Marketing and Sponsorship(Typical Subject (one of the following):)'),
(DEFAULT,6 ,'Current Issues in Sport Management(Complementary Subject (one of the following):)'),
(DEFAULT,6 ,'Quantitative Methods in Management(Complementary Subject (one of the following):)'),
(DEFAULT,6 ,'Internship'),
(DEFAULT,12 ,'Free Choice**'),
(DEFAULT,6 ,'Final Thesis'),
(DEFAULT,6 ,'Introduction to Linear Algebra and Discrete Mathematics'),
(DEFAULT,9 ,'Introduction to Programming'),
(DEFAULT,6 ,'Accounting for Decision Making'),
(DEFAULT,9 ,'Economics of Digital Markets'),
(DEFAULT,6 ,'Introduction to Analysis and Optimization Techniques'),
(DEFAULT,0 ,'Module 1: Data and Process Modeling for Business Informatics(Modeling and Databases)'),
(DEFAULT,6 ,'Application Engineering for Business Informatics'),
(DEFAULT,6 ,'Web and Internet Engineering'),
(DEFAULT,0 ,"'Module 1: Strategic Management and Digital Business(Introduction to Digital Business, Strategy and Management )'"),
(DEFAULT,12 ,'Specialization in Digital Finance and Financial Markets or in Digital Market and Advertising*'),
(DEFAULT,6 ,'Data Structures and Algorithms'),
(DEFAULT,6 ,'Probability Theory and Statistics'),
(DEFAULT,6 ,'Management of System Security and Networks'),
(DEFAULT,3 ,'English for Informatics and Digital Business'),
(DEFAULT,0 ,'Module 1: IT Management and Enterprise Modeling(IT Management and ERP Systems)'),
(DEFAULT,6 ,'Engineering of Mobile Systems'),
(DEFAULT,0 ,'Module 1: Introduction to Data Mining(Data Mining and Decision Making)'),
(DEFAULT,12 ,'Free Choice'),
(DEFAULT,3 ,'Legal Aspects of IT'),
(DEFAULT,3 ,'Italian/German for Informatics and Digital Business'),
(DEFAULT,6 ,'Seminar in Business Informatics and Information Systems'),
(DEFAULT,6 ,'Specialisation in Digital Finance and Financial Markets or in Digital Market and Advertising*'),
(DEFAULT,6 ,'Software Project Management'),
(DEFAULT,6 ,'Internship/Project'),
(DEFAULT,5 ,'Thesis'),
(DEFAULT,6 ,'M-1 Macroeconomics(Economics for Accounting and Finance)'),
(DEFAULT,6 ,'Applied Statistics for Accounting  and Finance'),
(DEFAULT,6 ,'Advanced Accounting'),
(DEFAULT,6 ,'Advanced Financial Statement Analysis'),
(DEFAULT,3 ,"'Data Analytics, Big Data and Blockchain'"),
(DEFAULT,6 ,'Financial Mathematics'),
(DEFAULT,9 ,'Advanced  Corporate Finance (FIN II)'),
(DEFAULT,6 ,'Advanced Business Law'),
(DEFAULT,6 ,'Advanced Auditing'),
(DEFAULT,6 ,'Advanced Taxation Law'),
(DEFAULT,6 ,'Corporate Bankruptcy and Reorganisation'),
(DEFAULT,3 ,'Lab in CPA exam'),
(DEFAULT,3 ,'Advanced Specialized Language Course for Accounting and Finance 1*'),
(DEFAULT,3 ,'Advanced Specialized Language Course for Accounting and Finance 2*'),
(DEFAULT,6 ,'Academic Writing and Research Skills*'),
(DEFAULT,6 ,'International Contract Law(Complementary Subject (one of the following):)'),
(DEFAULT,12 ,'Free Choice**'),
(DEFAULT,6 ,'Internship'),
(DEFAULT,15 ,'Final Thesis'),
(DEFAULT,6 ,'M-1 Macroeconomics(Economics for Accounting and Finance)'),
(DEFAULT,6 ,'Applied Statistics for Accounting and Finance'),
(DEFAULT,6 ,'Advanced Accounting'),
(DEFAULT,6 ,'Advanced Financial Statement Analysis'),
(DEFAULT,3 ,"'Data Analytics, Big Data and Blockchain'"),
(DEFAULT,6 ,'Financial Mathematics'),
(DEFAULT,9 ,'Advanced Corporate Finance (FIN II)'),
(DEFAULT,6 ,'Advanced Business Law'),
(DEFAULT,6 ,"'Corporate Restructuring, M&A (FIN II)'"),
(DEFAULT,6 ,'Risk Management and Derivatives'),
(DEFAULT,6 ,'Financial Econometrics'),
(DEFAULT,3 ,'Lab in Financial Trading'),
(DEFAULT,3 ,'Advanced Specialized Language Course for Accounting and Finance 1*'),
(DEFAULT,3 ,'Advanced Specialized Language Course for Accounting and Finance 2*'),
(DEFAULT,6 ,'Academic Writing and Research Skills*'),
(DEFAULT,6 ,'Banking and Financial Law(Complementary Subjects (one of the following):)'),
(DEFAULT,12 ,'Free Choice Courses**'),
(DEFAULT,6 ,'Internship'),
(DEFAULT,15 ,'Final thesis'),
(DEFAULT,6 ,'M-1 Macroeconomics(Economics for Accounting and Finance)'),
(DEFAULT,6 ,'Applied Statistics for Accounting  and Finance'),
(DEFAULT,6 ,'Advanced Accounting'),
(DEFAULT,6 ,'Advanced Financial Statement Analysis'),
(DEFAULT,3 ,"'Data Analytics, Big Data and Blockchain'"),
(DEFAULT,6 ,'Financial Mathematics'),
(DEFAULT,9 ,'Advanced Corporate Finance (FIN II)'),
(DEFAULT,6 ,'Advanced Business Law'),
(DEFAULT,6 ,'Measuring and Driving Corporate Performance'),
(DEFAULT,6 ,'Modeling Financial statement'),
(DEFAULT,6 ,'Advanced Strategic Management'),
(DEFAULT,3 ,'Lab in Advanced Communication in Business'),
(DEFAULT,3 ,'Advanced Specialized Language Course for Accounting and Finance 1*'),
(DEFAULT,3 ,'Advanced Specialized Language Course for Accounting and Finance 2*'),
(DEFAULT,6 ,'Advanced Writing and Research Skills*'),
(DEFAULT,6 ,'Corporate Bankruptcy and Reorganization(Complementary Subject (one of the following):)'),
(DEFAULT,12 ,'Free Choice Courses**'),
(DEFAULT,5 ,'Internship'),
(DEFAULT,15 ,'Final thesis'),
(DEFAULT,6 ,'M-1 Design Thinking and Prototyping**(Growth Mindset)'),
(DEFAULT,6 ,'M-1 Business Economics(Economics for Management)'),
(DEFAULT,9 ,'Foundations of Entrepreneurship**'),
(DEFAULT,6 ,'Statistical Methods for Business Analysis'),
(DEFAULT,6 ,'Service Design(1 of the following:)'),
(DEFAULT,9 ,'Entrepreneurial Finance and Venture Capital(1 of the following:)'),
(DEFAULT,6 ,'Free Choice Course*'),
(DEFAULT,6 ,'Entrepreneurial Marketing'),
(DEFAULT,8 ,'Startups Law and Industrial Law'),
(DEFAULT,6 ,'Free Choice Course*'),
(DEFAULT,6 ,'Social Entrepreneurship(2 of the following:)'),
(DEFAULT,7 ,'Entrepreneurship Lab - for start-ups**(1 of the following:)'),
(DEFAULT,6 ,'Internship'),
(DEFAULT,15 ,'Thesis'),
(DEFAULT,6 ,'Economics of the Public Sector'),
(DEFAULT,6 ,'Economic Policy'),
(DEFAULT,6 ,'Management and Organization in the Public Sector'),
(DEFAULT,6 ,'Human Resource Management in the Public Sector'),
(DEFAULT,6 ,'Accounting for the Public Sector'),
(DEFAULT,6 ,'M-1 Introduction to Statistical Methods(Statistics for the Public Sector)'),
(DEFAULT,6 ,'M-1 Theory and Laboratory of Public Law and Sources of Law(Public and Administrative Law)'),
(DEFAULT,33 ,'Italian/German/English: Advanced Specialized Language Course*'),
(DEFAULT,3 ,'Management Information Systems in the Public Sector'),
(DEFAULT,12 ,'Free Choice Courses**'),
(DEFAULT,6 ,'Topics in Public Economics(Complementary Subjects - students have to choose one of the following subjects:)'),
(DEFAULT,4 ,'Internship'),
(DEFAULT,15 ,'Final thesis'),
(DEFAULT,8 ,'Comparative Public Policy'),
(DEFAULT,6 ,'Management and Organization of Public Services(Complementary Subjects - students have to choose two of the following subjects:)'),
(DEFAULT,8 ,'Institutional Communication and Public Project Management'),
(DEFAULT,6 ,'Advanced Accounting for Public Sector(Complementary Subjects - students choose two of the following subjects:)'),
(DEFAULT,6 ,'Elements of Linguistic Theory I'),
(DEFAULT,6 ,'Principles of Sociology'),
(DEFAULT,6 ,'Techniques of Visual Communication(Techniques of Visual Communication and Music as Communication)'),
(DEFAULT,6 ,"'Statistics and Methodology in Culture, Economics and Society'"),
(DEFAULT,6 ,'Anthropology of Intercultural Processes'),
(DEFAULT,6 ,'Psychology of Communication'),
(DEFAULT,6 ,'Marketing and Communication: Theory and Instruments'),
(DEFAULT,6 ,'Elements of Computer Science for Communications'),
(DEFAULT,6 ,'Optional Subjects'),
(DEFAULT,6 ,'Elements of Linguistic Theory II'),
(DEFAULT,6 ,'Media and Society(Media and Society and Cultural Studies)'),
(DEFAULT,6 ,'Sociology of Culture'),
(DEFAULT,6 ,'Design in Virtual Environments for Communication(Design in Virtual Environments for Communication and Media Education)'),
(DEFAULT,6 ,'Management of Non-Profit and Cultural Organizations'),
(DEFAULT,6 ,'Culture and Aesthetics'),
(DEFAULT,6 ,'Language and Translation – German Language'),
(DEFAULT,6 ,'Optional Subjects Related to the Branch of Study'),
(DEFAULT,6 ,'Communication in Social and Political Campaigns(Communication in Social and Political Campaigns and Social media)'),
(DEFAULT,6 ,'Sustainable Development'),
(DEFAULT,6 ,'Theory and Techniques of Measuring Cultural and Socio-Economic Phenomena'),
(DEFAULT,6 ,'Media Law'),
(DEFAULT,6 ,'Institutional Communication'),
(DEFAULT,12 ,'Internship'),
(DEFAULT,12 ,'Final Exam'),
(DEFAULT,5 ,'General Pedagogy(General and Social Pedagogy)'),
(DEFAULT,10 ,'General Sociology'),
(DEFAULT,5 ,'General Psychology(General and Developmental Psychology)'),
(DEFAULT,5 ,'Social Legislation(Social and Juvenile Legislation)'),
(DEFAULT,5 ,'Methods and Teaching of Physical Education'),
(DEFAULT,5 ,'Social Psychology'),
(DEFAULT,5 ,'Empirical Pedagogy'),
(DEFAULT,5 ,'Sociology of Deviance(Behaviour and Sociology of Communicative and Cultural Processes)'),
(DEFAULT,5 ,"'Special Needs in Education(Special Needs in Education, Technology for Inclusive Education)'"),
(DEFAULT,5 ,'English'),
(DEFAULT,5 ,'Psychology of Education'),
(DEFAULT,5 ,'Politics'),
(DEFAULT,3 ,'Computer Skills for Education'),
(DEFAULT,9 ,'Optional Subjects'),
(DEFAULT,8 ,'Internship'),
(DEFAULT,5 ,'Media Education'),
(DEFAULT,5 ,'Intercultural Pedagogy(Intercultural Pedagogy and Adult Education)'),
(DEFAULT,5 ,"'Hygiene(Hygiene and Prevention, Health Promotion and Social Medicine)'"),
(DEFAULT,5 ,'Social Statistics'),
(DEFAULT,5 ,'Cultural Anthropology'),
(DEFAULT,5 ,'German or Italian'),
(DEFAULT,8 ,'Internship'),
(DEFAULT,6 ,'Optional Subjects'),
(DEFAULT,6 ,'Final exam'),
(DEFAULT,6 ,'Quantitative Analysis of Social Phenomena and Population Dynamics'),
(DEFAULT,6 ,'Introduction to Scientific Work and Qualitative Social Research'),
(DEFAULT,6 ,'General Sociology'),
(DEFAULT,6 ,"'Social Work Theories, Principles and Ethics(Introduction to Social Work and Social Policy)'"),
(DEFAULT,6 ,'Public Law and Fundamental Rights Protection'),
(DEFAULT,6 ,'General Psychology'),
(DEFAULT,5 ,'Fields and Organization of Social Work Practice(Social Work Methodology and Organization)'),
(DEFAULT,4 ,'Optional Subjects'),
(DEFAULT,4 ,'Orientation Placement'),
(DEFAULT,6 ,'Social Work Methods 2'),
(DEFAULT,5 ,"'Inter- and transnational Social Work(Social Work in historical, inter- and transnational contexts)'"),
(DEFAULT,6 ,"'Body, Gender and Family in Transcultural Perspective'"),
(DEFAULT,9 ,'Developmental and Educational Psychology'),
(DEFAULT,6 ,'Mental Health and Illness in the Life Cycle'),
(DEFAULT,6 ,'Social Pedagogy throughout the Life Cycle'),
(DEFAULT,6 ,'Juvenile and Family Law'),
(DEFAULT,11 ,'Field Placement and Critical Reflection (lab.)'),
(DEFAULT,6 ,"'Actors, Sectors and Spaces of Welfare(Local Welfare Development)'"),
(DEFAULT,5 ,'Social Work Methods 3'),
(DEFAULT,6 ,'Social Psychology'),
(DEFAULT,6 ,'Penal and Penitentiary Law'),
(DEFAULT,6 ,"'Social Change, Diversity and Inclusion'"),
(DEFAULT,2 ,'English for Professional and Academic Purposes'),
(DEFAULT,2 ,'Information and Communication Technology for Social Work (lab.)'),
(DEFAULT,8 ,'Optional Subjects'),
(DEFAULT,7 ,'Project Placement'),
(DEFAULT,6 ,'Final Module (research lab.  final thesis  final exam)'),
(DEFAULT,6 ,'Advanced Issues in Linguistics(Linguistics)'),
(DEFAULT,6 ,'Romance Linguistics'),
(DEFAULT,6 ,'Computer programming (Python)(Computer Science)'),
(DEFAULT,6 ,'General Sociology'),
(DEFAULT,3 ,'Minority Language'),
(DEFAULT,6 ,'Sociolinguistics and Multilingualism(Sociolinguistics)'),
(DEFAULT,6 ,'Language Variation and Change'),
(DEFAULT,6 ,'German Dialectology'),
(DEFAULT,6 ,'Cultural Anthropology(Anthropology)'),
(DEFAULT,6 ,'Quantitative Methods in Linguistics(Quantitative Linguistics)'),
(DEFAULT,8 ,'Optional Subjects'),
(DEFAULT,6 ,'Language Acquisition(Language acquisition and language policy)'),
(DEFAULT,6 ,'Linguistic rights'),
(DEFAULT,6 ,'Internship'),
(DEFAULT,23 ,'Final exam'),
(DEFAULT,6 ,'Quantitative Methods in Linguistics(Quantitative Linguistics)'),
(DEFAULT,8 ,'Optional Subject'),
(DEFAULT,6 ,'Computer Linguistics(Computer Linguistics)'),
(DEFAULT,6 ,'Machine Learning'),
(DEFAULT,6 ,'Internship'),
(DEFAULT,23 ,'Final exam'),
(DEFAULT,6 ,'Social Work and Social Theory(Theory and Research in Social Work)'),
(DEFAULT,6 ,'Community Work and Participation'),
(DEFAULT,6 ,'Social Policy Between Global Change and Local Challenges(Social Policy and Welfare Production)'),
(DEFAULT,6 ,'Quantitative Methods and Social Research'),
(DEFAULT,6 ,"'Labour and Social Security Law(Labour Dymanics, Social Security and Administrative Action)'"),
(DEFAULT,6 ,'Psychology of Care and Personnel Development in Social Work'),
(DEFAULT,4 ,'Digital Ecology'),
(DEFAULT,4 ,'Professional Placement'),
(DEFAULT,6 ,'Participatory Design and Evaluation of Innovative Social Interventions and Services'),
(DEFAULT,6 ,'Inter-and Transcultural Approaches in Communicative and Organizational Processes(Values and Ethics in Cultural and Professional Contexts)'),
(DEFAULT,6 ,'Administration and Economic Management of Social Services(Social Entrepreneurship and Economic Management of Social Services)'),
(DEFAULT,6 ,'Criminal Justice and Social Work'),
(DEFAULT,4 ,'Integrated Social Planning'),
(DEFAULT,4 ,'English for Social Work'),
(DEFAULT,6 ,'Project or Research Placement'),
(DEFAULT,12 ,'Final Exam”'),
(DEFAULT,12 ,'Perspectives on music making and learning'),
(DEFAULT,6 ,'Ethnomusicology'),
(DEFAULT,6 ,'Music Paleography and Philology'),
(DEFAULT,6 ,'Cultural Anthropology'),
(DEFAULT,6 ,'German Literature'),
(DEFAULT,12 ,'Optional courses'),
(DEFAULT,12 ,'Internship'),
(DEFAULT,6 ,'Theoretical and methodological basics of communicating music (Musikvermittlung)'),
(DEFAULT,6 ,'Forms and techniques of communicating music (Musikvermittlung): thematic insights'),
(DEFAULT,6 ,'History of theatre and musical dramaturgy'),
(DEFAULT,6 ,'Planning and evaluation of learning pathways'),
(DEFAULT,6 ,'Study of musical sources'),
(DEFAULT,6 ,'Aesthetic Education'),
(DEFAULT,33 ,'Scientific language skills'),
(DEFAULT,18 ,'Final exam'),
(DEFAULT,6 ,'Music Philology'),
(DEFAULT,6 ,'Stylistics of the modern and contemporary music'),
(DEFAULT,6 ,'Musical Dramaturgy'),
(DEFAULT,6 ,'History of art criticism'),
(DEFAULT,6 ,'Codicology'),
(DEFAULT,6 ,'Archival studies I or Paleography II'),
(DEFAULT,33 ,'Scientific language skills'),
(DEFAULT,18 ,'Final exam'),
(DEFAULT,9 ,'Mathematics and Applied Statistics'),
(DEFAULT,8 ,'Fundamentals of Chemistry'),
(DEFAULT,6 ,'Botany(Plant and Animal Biology )'),
(DEFAULT,6 ,'Fundamentals of Physics'),
(DEFAULT,3 ,'Applied Informatics'),
(DEFAULT,6 ,'Plant Genetics'),
(DEFAULT,6 ,'Agribusiness Administration and Finance'),
(DEFAULT,6 ,'Agricultural Ecology and Principles of Plant Production'),
(DEFAULT,6 ,'Principles of Tree Cultivation'),
(DEFAULT,6 ,'Agricultural Machinery'),
(DEFAULT,6 ,'Soil Chemistry and Fertility'),
(DEFAULT,6 ,"'Agricultural Economics and Policy(Agricultural Economics, Policy and Law )'"),
(DEFAULT,6 ,'Entomology(Entomology and Phytopathology )'),
(DEFAULT,6 ,'Biochemistry and Physiology of Agricultural Plants'),
(DEFAULT,9 ,'Biology of Micro-organisms and Agricultural Microbiology(Microbiology and Agro-industries )'),
(DEFAULT,5 ,'Internship'),
(DEFAULT,5 ,'Final Exam'),
(DEFAULT,6 ,'Rural Appraisal'),
(DEFAULT,9 ,'Hydrology and Hydraulics'),
(DEFAULT,6 ,'Plant Protection'),
(DEFAULT,6 ,'Animal Breeding and Animal Husbandry(Animal Breeding and Grassland Management )'),
(DEFAULT,6 ,'Fruit Production'),
(DEFAULT,12 ,'Free choice courses**'),
(DEFAULT,9 ,'Hydrology and Hydraulics(Rural Appraisal  )'),
(DEFAULT,6 ,'Forestry(Forestry and Forest Ecology )'),
(DEFAULT,6 ,'Environmental Geomatics and Remote Sensing'),
(DEFAULT,12 ,'Free choice courses**'),
(DEFAULT,6 ,'Rural Appraisal'),
(DEFAULT,9 ,'Food Microbiology'),
(DEFAULT,6 ,'Protection of the Stored Products'),
(DEFAULT,6 ,'Unit Operations in Food Engineering(Food Technologies )'),
(DEFAULT,6 ,'Analytical Chemistry'),
(DEFAULT,12 ,'Free choice courses**'),
(DEFAULT,10 ,'Mathematical Analysis I'),
(DEFAULT,6 ,'General and Inorganic Chemistry'),
(DEFAULT,8 ,'Geometry'),
(DEFAULT,6 ,'Fundamentals of Information Science and Microcontroller Programming'),
(DEFAULT,8 ,'Physics I'),
(DEFAULT,10 ,'Mathematical Analysis II'),
(DEFAULT,6 ,'Technical Drawing and Industrial Engineering Methods'),
(DEFAULT,6 ,'Materials Science and Technology(Materials Science and Structural Mechanics)'),
(DEFAULT,6 ,'Physics II'),
(DEFAULT,10 ,'Production Systems and Industrial Logistics'),
(DEFAULT,6 ,'Electrical circuits and Machines'),
(DEFAULT,10 ,'Engineering Thermodynamics and Heat Transfer'),
(DEFAULT,6 ,'Classical Mechanics'),
(DEFAULT,6 ,'Fluid Mechanics'),
(DEFAULT,12 ,'Free Choice Courses*'),
(DEFAULT,6 ,'Internship'),
(DEFAULT,10 ,'Mechanics of Machinery'),
(DEFAULT,8 ,'Fluid Machines'),
(DEFAULT,6 ,'Fundamentals of Machine Design'),
(DEFAULT,6 ,'Machine Design'),
(DEFAULT,8 ,'Manufacturing Technology'),
(DEFAULT,8 ,'Factory and Plant planning'),
(DEFAULT,3 ,'Specialized Language'),
(DEFAULT,3 ,'Final Exam'),
(DEFAULT,10 ,'Mathematical Analysis I'),
(DEFAULT,6 ,'General and Inorganic Chemistry'),
(DEFAULT,8 ,'Geometry'),
(DEFAULT,6 ,'Fundamentals of Information Science and Microcontroller Programming'),
(DEFAULT,8 ,'Physics I'),
(DEFAULT,10 ,'Mathematical Analysis II'),
(DEFAULT,6 ,'Materials Science and Technology(Materials Science and Structural Mechanics)'),
(DEFAULT,6 ,'Physics II'),
(DEFAULT,10 ,'Production Systems and Industrial Logistics'),
(DEFAULT,6 ,'Electrical circuits and Machines'),
(DEFAULT,10 ,'Engineering Thermodynamics and Heat Transfer'),
(DEFAULT,6 ,'Classical Mechanics'),
(DEFAULT,6 ,'Fluid Mechanics'),
(DEFAULT,12 ,'Free Choice Courses*'),
(DEFAULT,6 ,'Internship'),
(DEFAULT,10 ,'Mechanics of Machinery'),
(DEFAULT,8 ,'Fluid Machines'),
(DEFAULT,6 ,'Industrial Electrical Applications'),
(DEFAULT,6 ,'Fundamentals of Machine Design'),
(DEFAULT,6 ,'Advanced Methods for Fluid Machine Design'),
(DEFAULT,8 ,'Engineering Energetics'),
(DEFAULT,8 ,'Factory and Plant planning'),
(DEFAULT,3 ,'Specialized Language'),
(DEFAULT,3 ,'Final Exam'),
(DEFAULT,10 ,'Mathematical Analysis I'),
(DEFAULT,6 ,'General and Inorganic Chemistry'),
(DEFAULT,8 ,'Geometry'),
(DEFAULT,6 ,'Fundamentals of Information Science and Microcontroller Programming'),
(DEFAULT,8 ,'Physics I'),
(DEFAULT,10 ,'Mathematical Analysis II'),
(DEFAULT,6 ,'Technical Drawing and Industrial Engineering Methods'),
(DEFAULT,6 ,'Materials Science and Technology(Materials Science and Structural Mechanics)'),
(DEFAULT,6 ,'Physics II'),
(DEFAULT,10 ,'Production Systems and Industrial Logistics'),
(DEFAULT,6 ,'Electrical circuits and Machines'),
(DEFAULT,10 ,'Engineering Thermodynamics and Heat Transfer'),
(DEFAULT,6 ,'Operations Research'),
(DEFAULT,6 ,'Economics for Engineers'),
(DEFAULT,12 ,'Free Choice Courses*'),
(DEFAULT,6 ,'Internship'),
(DEFAULT,8 ,'Digital Production Planning and Quality Control'),
(DEFAULT,6 ,'Logistics and Transport'),
(DEFAULT,8 ,'Factory and Plant planning'),
(DEFAULT,8 ,'Manufacturing Technology'),
(DEFAULT,10 ,'Mechanics of Machinery'),
(DEFAULT,6 ,'Fundamentals of Machine Design'),
(DEFAULT,3 ,'Specialized Language'),
(DEFAULT,3 ,'Final Exam'),
(DEFAULT,10 ,'Mathematical Analysis I'),
(DEFAULT,6 ,'Economics for Engineers'),
(DEFAULT,8 ,'Geometry'),
(DEFAULT,6 ,'Fundamentals of Information Science and Microcontroller Programming'),
(DEFAULT,8 ,'Physics I'),
(DEFAULT,10 ,'Mathematical Analysis II'),
(DEFAULT,3 ,'Specialized Language'),
(DEFAULT,10 ,'Mechanics of Machines and Mechanism for Automation'),
(DEFAULT,6 ,'Physics II'),
(DEFAULT,6 ,'Materials Science and Technology(Materials Science and Structural Mechanics)'),
(DEFAULT,6 ,'Engineering Thermodynamics and Heat Transfer for Mechatronics'),
(DEFAULT,6 ,'Fundamentals of Hydraulics and Pneumatics'),
(DEFAULT,8 ,'Digital Production Planning and Quality Control'),
(DEFAULT,12 ,'Free Choice Courses*'),
(DEFAULT,6 ,'Internship'),
(DEFAULT,6 ,'Systems and Control(Systems and Control)'),
(DEFAULT,10 ,'Production Systems and Industrial Logistics'),
(DEFAULT,8 ,'Factory and Plant planning'),
(DEFAULT,6 ,'Electrical circuits and Machines'),
(DEFAULT,6 ,'Programmable Controllers for Industrial Automation'),
(DEFAULT,6 ,'Fundamentals of Machine Design'),
(DEFAULT,6 ,'Optimization'),
(DEFAULT,6 ,'Reverse Engineering und Rapid Prototyping'),
(DEFAULT,3 ,'Final Exam'),
(DEFAULT,6 ,'Mathematics'),
(DEFAULT,6 ,'Fundamentals of Information Science and Microcontroller Programming'),
(DEFAULT,6 ,"'Economy, Law, Contracts'"),
(DEFAULT,6 ,'Wood Chemistry'),
(DEFAULT,6 ,'Physics'),
(DEFAULT,6 ,'Wood Anatomy and Productive Forestry'),
(DEFAULT,10 ,'Product Design'),
(DEFAULT,6 ,'Fundamentals of Programming'),
(DEFAULT,6 ,'Technical Drawing - CAD'),
(DEFAULT,3 ,'Specialised Language'),
(DEFAULT,6 ,"'Logging, sawmill operations and traceability procedures of wood(Complementary Subject (one of the following):)'"),
(DEFAULT,6 ,'Heat and Mass Transfer'),
(DEFAULT,6 ,'Material Sciences'),
(DEFAULT,6 ,'Industrial Production Organization and Management'),
(DEFAULT,6 ,"'Electronics, Diagnosis and Quality Control'"),
(DEFAULT,6 ,'Manufacturing Technology'),
(DEFAULT,6 ,'Energy Efficiency in Wood Production and Final Use'),
(DEFAULT,6 ,'Mechatronics and Process Automation'),
(DEFAULT,6 ,'Industrial Plants and Logistics'),
(DEFAULT,3 ,'Final Exam'),
(DEFAULT,6 ,'Mathematics'),
(DEFAULT,6 ,'Fundamentals of Information Science and Microcontroller programming'),
(DEFAULT,6 ,"'Economy, Law, Contracts'"),
(DEFAULT,6 ,'Wood Chemistry'),
(DEFAULT,6 ,'Physics'),
(DEFAULT,6 ,'Wood Anatomy and Productive Forestry'),
(DEFAULT,10 ,'Product Design'),
(DEFAULT,6 ,'Fundamentals of Programming'),
(DEFAULT,6 ,'Technical Drawing - CAD'),
(DEFAULT,3 ,'Specialized Language'),
(DEFAULT,6 ,'Heat and Mass Transfer'),
(DEFAULT,6 ,'Material Sciences'),
(DEFAULT,6 ,'Construction Site 4.0'),
(DEFAULT,6 ,'Mechanics of Structures'),
(DEFAULT,6 ,'Energy Efficiency in Wood Production and Final Use'),
(DEFAULT,6 ,"'High-Performance Buildings: Comfort, Energy Efficiency'"),
(DEFAULT,6 ,'High-Performance Buildings: Seismic Design and Fire Resistance'),
(DEFAULT,6 ,'Mechatronics and Process Automation'),
(DEFAULT,6 ,'Operational Safety and LCA'),
(DEFAULT,3 ,'Evaluation Final Exam'),
(DEFAULT,6 ,'Electrical Systems Engineering'),
(DEFAULT,9 ,'Fluid Machines Engineering'),
(DEFAULT,6 ,"'Engineering Thermodynamics, Heat and Mass Transfer'"),
(DEFAULT,4 ,'Environmental Fluid Mechanics(Environmental Fluid Mechanics/ Hydropower Plants)'),
(DEFAULT,9 ,'Building HVAC Systems'),
(DEFAULT,9 ,'Advanced Applications of Building Physics'),
(DEFAULT,6 ,'Electric Power Conversion Equipment'),
(DEFAULT,3 ,'Italiano Tecnico / Technisches Italienisch(One exam from the following two subjects:)'),
(DEFAULT,6 ,"'Thermal Engines(Power Production, CHP and District Heating Systems)'"),
(DEFAULT,6 ,'Special Issues of Building Physics'),
(DEFAULT,6 ,'Technologies and Production Processes for Energy Engineering(Applied Mechanics and Technologies for Energy Efficiency)'),
(DEFAULT,6 ,'Wind Powers Systems(Hydropower and Wind Power System)'),
(DEFAULT,3 ,'Fundamentals of Structural Mechanics(Mechanics and Structural Design for Energy Engineering)'),
(DEFAULT,6 ,'Advanced Materials for Energy Engineering'),
(DEFAULT,6 ,'District Heating System Design'),
(DEFAULT,6 ,'Electrochemical Energy Storage and Conversion(One exam from the following two subjects:)'),
(DEFAULT,12 ,'Optional Subjects'),
(DEFAULT,15 ,'Master Degree Thesis'),
(DEFAULT,6 ,'Landscape Ecology'),
(DEFAULT,0 ,'Geomatics and Landscape Planning(Advanced English (C1-Level))'),
(DEFAULT,6 ,'Management of Mountain Forests'),
(DEFAULT,3 ,'Environmental Economics(Basics of Environmental Economics and Natural Risk Management)'),
(DEFAULT,3 ,'Applied Statistics'),
(DEFAULT,0 ,'Sustainable Development of Mountain Areas'),
(DEFAULT,3 ,"'Project Development and Management(Economic Development, Sustainable Tourism and Regional Products )'"),
(DEFAULT,3 ,'Ecosystem Restoration(Ecosystem Restoration and Rural Appraisal)'),
(DEFAULT,6 ,'Technologies for Low Input Agricultural Systems'),
(DEFAULT,4 ,'Mountain Agriculture(Sustainable Farming Systems in Mountain Areas)'),
(DEFAULT,25 ,"'Free Choice Courses* (at Faculty of Biology, University of Innsbruck)'"),
(DEFAULT,5 ,"'Selected topics in environmental management (one mandatory course at Faculty of Biology, University of Innsbruck)'"),
(DEFAULT,30 ,'Thesis** (at either Free University of Bozen-Bolzano or University of Innsbruck)'),
(DEFAULT,6 ,'Landscape Ecology'),
(DEFAULT,3 ,'Advanced English (C1-Level)'),
(DEFAULT,3 ,'Geomatics(Geomatics and Landscape Planning)'),
(DEFAULT,6 ,'Management of Mountain Forests'),
(DEFAULT,3 ,'Environmental Economics(Basics of Environmental Economics and Natural Risk Management )'),
(DEFAULT,3 ,'Applied Statistics'),
(DEFAULT,3 ,'Applied Botany(Nature Conservation and Management )'),
(DEFAULT,3 ,'Protection Forestry(Forest Planning and Protection Forestry )'),
(DEFAULT,3 ,'Hydromorphology of Mountain Rivers(Management of Mountain Rivers )'),
(DEFAULT,3 ,'Advanced Geomatics(Advanced Geomatics and Environmental Impact Assessment)'),
(DEFAULT,25 ,"'Free Choice Courses* (at Faculty of Biology, University of Innsbruck)'"),
(DEFAULT,5 ,"'Selected Topics in Environmental Management (one mandatory course at Faculty of Biology, University of Innsbruck)'"),
(DEFAULT,30 ,'Thesis** (at either Free University of Bozen-Bolzano or University of Innsbruck)'),
(DEFAULT,6 ,'Unit Operations in Food Processing(Innovation and Authenticity in Food Processing)'),
(DEFAULT,8 ,'Fermentations as Tools for Making Traditional and Innovative Foods and Beverages'),
(DEFAULT,6 ,'Food Chemistry'),
(DEFAULT,6 ,'Food Value Chain Management'),
(DEFAULT,3 ,'Computer Application in Food Sciences'),
(DEFAULT,6 ,'Reaction Kinetics in Food Processing'),
(DEFAULT,8 ,'Environmental Chemistry Towards Food Processing'),
(DEFAULT,6 ,"'The Natural Microbial Starters for Innovation and Authenticity(Starter and Functional Microbes for Innovation, Authenticity and Healthy Status )'"),
(DEFAULT,6 ,'Food Processing Equipment'),
(DEFAULT,6 ,'Genetics Applied to Foods'),
(DEFAULT,6 ,'Sensors and Biosensors for Food Processing'),
(DEFAULT,8 ,'Free Choice Courses*'),
(DEFAULT,33 ,'Thesis'),
(DEFAULT,6 ,'Food Structure Control and Management'),
(DEFAULT,6 ,'Quality System Development and Management and Shelf Life Assessment of Food'),
(DEFAULT,6 ,'Sample Preparation Techniques and Analysis of Contaminants'),
(DEFAULT,8 ,'Free Choice Courses*'),
(DEFAULT,33 ,'Thesis'),
(DEFAULT,6 ,'Human Nutrition'),
(DEFAULT,6 ,'Applied Human Nutrition'),
(DEFAULT,6 ,'Industrial Microbiology for Food Quality Improvement'),
(DEFAULT,8 ,'Free Choice Courses*'),
(DEFAULT,33 ,'Thesis'),
(DEFAULT,5 ,'Chemistry of Food Proteins'),
(DEFAULT,5 ,'Cheese and Fermented Dairy Foods'),
(DEFAULT,5 ,'Meat Science and Technology'),
(DEFAULT,11 ,'Free Choice Courses*'),
(DEFAULT,33 ,'Thesis'),
(DEFAULT,5 ,'Introduction to Packaging Technology'),
(DEFAULT,5 ,'Packaging Technology  – Mechanical Processes'),
(DEFAULT,5 ,'Beverage Process Engineering'),
(DEFAULT,11 ,'Free Choice Courses*'),
(DEFAULT,33 ,'Thesis'),
(DEFAULT,5 ,'Reverse Engineering and Rapid Prototyping(Design and Manufacturing of Industrial Products)'),
(DEFAULT,5 ,"'Project Management(Project, Process and Technology Management )'"),
(DEFAULT,5 ,'Automatic Control'),
(DEFAULT,5 ,'Functional Mechanical Design'),
(DEFAULT,5 ,'Mechatronics and Robotics(Industrial Automation and Digital Manufacturing)'),
(DEFAULT,5 ,'Thermo-Mechanicals Measurements'),
(DEFAULT,5 ,'Digital Factory and Industrial Maintenance'),
(DEFAULT,5 ,'Mobile Robotics'),
(DEFAULT,5 ,'Electric Drives and Machines'),
(DEFAULT,5 ,'Programmable Controllers for Industrial Automation'),
(DEFAULT,5 ,'AI Applications in Industry'),
(DEFAULT,5 ,'Free choice course'),
(DEFAULT,5 ,'Free choice course'),
(DEFAULT,5 ,'Free choice course'),
(DEFAULT,5 ,'Study project'),
(DEFAULT,30 ,'Thesis'),
(DEFAULT,5 ,'Reverse Engineering and Rapid Prototyping(Design and Manufacturing of Industrial Products)'),
(DEFAULT,5 ,"'Project Management(Project, Process and Technology Management )'"),
(DEFAULT,5 ,'Automatic Control'),
(DEFAULT,5 ,'Management Control and Business Planning'),
(DEFAULT,5 ,'Mechatronics and Robotics(Industrial Automation and Digital Manufacturing)'),
(DEFAULT,5 ,'Thermo-Mechanicals Measurements'),
(DEFAULT,5 ,'Digital Factory and Industrial Maintenance'),
(DEFAULT,5 ,'Digital Transformation and Sustainability Management'),
(DEFAULT,5 ,'Logistic strategies and methods (offered at OvGU Magdeburg)'),
(DEFAULT,5 ,'Supply Chain Practice / ERP (offered at OvGU Magdeburg)'),
(DEFAULT,5 ,'Business Decision Making (offered at OvGU Magdeburg)'),
(DEFAULT,5 ,'Free choice course (offered at OvGU Magdeburg)'),
(DEFAULT,5 ,'Study )Project (Individual or Team) - Laboratory in Mechanics/Automation'),
(DEFAULT,30 ,'Thesis')


Commit;